version: '3.8'
services:
    main: 
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - 8081:8000
        depends_on:
            - main_db
            
    main_db:
        image: mysql:5.7.33
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3308:3306